### ISSUE TITLE
Discuss SVG size hardcoded vs css.

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-socials#1]
I took away the hardcoded size in the svg partials as it removed the possibility of styling them with css and its advantage (responsiveness, hover etc...).

The problem is that for very low connections, the SVGs can appear very big before css loads. I believe we should counter this by having a `svg { width: 1rem}` in our css reset.

This would make sure the width of SVGs is initially not bigger than the default browser font size.

**Comment by budparr** [comment]
Try that on a slow connection in Firefox. Rendered very badly for Midisgroup because the svg loaded before CSS

**Comment by regisphilibert** [comment]
yes I'll try that. Thanks.
